---
name: Run tests
on:
  pull_request:
permissions: {}
jobs:
  test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.workflow.yml
    permissions:
      contents: read

  validate-docker:
    name: Validate Docker Build
    uses: ./.github/workflows/docker.workflow.yml
    permissions:
      contents: read
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    with:
      platform: ${{ matrix.platform }}
